# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_squashed_0025_remove_theme_json_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='folder',
            field=models.CharField(default='themes/default', max_length=1024),
        ),
    ]
