language: python
python:
  - "3.6"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - elasticsearch
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
  - psql -c "CREATE DATABASE opencanada;" -U postgres
  - psql -c "CREATE ROLE opencanada LOGIN PASSWORD 'opencanada';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE opencanada TO opencanada;" -U postgres
  - python manage.py migrate
  - python manage.py update_index
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
