language: python
python:
  - "3.4"
  - "2.7"
env:
  - DJANGO=1.9.12
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q six
  - pip install -r requirements/test.txt --use-mirrors
before_script:
  - flake8 .
#  - isort -c -rc .
script:
  - coverage run --source='.' ./manage.py test --settings opencanada.settings.test -v 3
after_success:
  - coveralls
