language: python
python:
  - "3.6"
services:
  - elasticsearch
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
  - python manage.py migrate
  - python manage.py update_index
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
