language: python
python:
  - "3.6"
services:
  - elasticsearch
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
  - python manage.py update_index
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
