language: python
python:
  - "3.6"
# env:
#   - DJANGO=2.0.9
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
before_script:
  - flake8 .
#  - isort -c -rc .
script:
  - python manage.py test
