# Generated by Django 2.0.13 on 2020-07-03 17:39

from django.db import migrations


def update_email(apps, schema_editor):
    SiteDefaults = apps.get_model('core', 'SiteDefaults')
    for default_setting in SiteDefaults.objects.all():
        default_setting.contact_email = 'info@thecic.org'
        default_setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20151016_0320'),
    ]

    operations = [
        migrations.RunPython(update_email),
    ]
