# Generated by Django 2.0.6 on 2018-07-03 18:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20170302_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedimage',
            name='collection',
            field=models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection'),
        ),
    ]
